version: '2'
services:
  database:
    image: mysql:5.7.20
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - 'MYSQL_ROOT_PASSWORD=rb7Dr3v31tV'
      - 'MYSQL_DATABASE=case-study'
    ports:
      - '33588:3306'
